spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: aws-service
          uri: http://localhost:8083
          predicates:
            - Path=/aws/**
        - id: vote-service
          uri: http://localhost:8087
          predicates:
            - Path=/vote/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true